const $ = id => document.getElementById(id);
let languages={},history=[],busy=false,recognition=null,recording=false,revision=0;
try{history=JSON.parse(localStorage.getItem('translationHistory')||'[]');if(!Array.isArray(history))history=[];}catch{history=[];}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function count(){const n=new TextEncoder().encode($('input').value).length;$('count').textContent=`${n} / 500 bytes`;$('count').style.color=n>500?'#b4425c':'';}
function invalidate(){revision++;$('output').value='';count();}
function saveHistory(){try{localStorage.setItem('translationHistory',JSON.stringify(history));}catch{}renderHistory();}
function renderHistory(){const list=$('historyList');list.replaceChildren();if(!history.length){const p=document.createElement('p');p.className='muted';p.textContent='Your recent translations will appear here.';list.append(p);return;}history.slice(0,8).forEach(item=>{const card=document.createElement('div');card.className='historyItem';const label=document.createElement('small');label.textContent=`${languages[item.source]||item.source} → ${languages[item.target]||item.target}`;const original=document.createElement('p');original.dir='auto';original.textContent=item.text;const translated=document.createElement('p');translated.dir='auto';translated.textContent=item.translation;card.append(label,original,translated);list.append(card);});}
async function translate(){if(busy)return;const text=$('input').value.trim();if(!text){status('Write a message first.',true);return;}if(new TextEncoder().encode(text).length>500){status('Shorten your message to 500 UTF-8 bytes.',true);return;}const source=$('source').value,target=$('target').value,requestRevision=revision;busy=true;$('translate').disabled=true;$('translate').textContent='Translating…';$('output').value='';status('Translating your message…');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,source,target}),signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Translation failed.');if(requestRevision!==revision){status('Your message changed. Click Translate again.');return;}$('output').value=result.translation;status('Translation complete.');history.unshift({text,translation:result.translation,source,target});history=history.slice(0,8);saveHistory();}catch(error){if(requestRevision===revision)status(error.name==='AbortError'?'The request timed out. Please try again.':error.message,true);}finally{clearTimeout(timer);busy=false;$('translate').disabled=false;$('translate').textContent='Translate';}}
$('translate').addEventListener('click',translate);
$('input').addEventListener('input',invalidate);
$('source').addEventListener('change',()=>{if(recording)recognition.stop();invalidate();});$('target').addEventListener('change',invalidate);
$('clear').addEventListener('click',()=>{if(recording)recognition.stop();$('input').value='';invalidate();status('Ready to translate.');$('input').focus();});
$('swap').addEventListener('click',()=>{if(recording)recognition.stop();const source=$('source').value;$('source').value=$('target').value;$('target').value=source;const previous=$('output').value;if(previous)$('input').value=previous;invalidate();status('Languages swapped.');});
$('copy').addEventListener('click',async()=>{if(!$('output').value){status('Translate a message before copying.',true);return;}try{await navigator.clipboard.writeText($('output').value);status('Translation copied.');}catch{status('Clipboard unavailable. Select the translation and press Ctrl+C.',true);}});
$('speak').addEventListener('click',()=>{if(!$('output').value){status('Translate a message first.',true);return;}if(!('speechSynthesis'in window)){status('Speech playback is unavailable in this browser.',true);return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance($('output').value);utterance.lang=$('target').value;utterance.onerror=()=>status('No suitable speech voice is available.',true);speechSynthesis.speak(utterance);});
$('clearHistory').addEventListener('click',()=>{history=[];saveHistory();});
function mode(voice){$('textTab').classList.toggle('active',!voice);$('voiceTab').classList.toggle('active',voice);$('record').hidden=!voice;$('heading').textContent=voice?'Let your voice cross languages.':'Make your words understood.';$('description').textContent=voice?'Select the spoken language, record one message, then translate. Swap languages for the other person.':'Choose your languages, write your message, and translate.';if(!voice&&recording)recognition.stop();}
$('textTab').onclick=()=>mode(false);$('voiceTab').onclick=()=>mode(true);
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.interimResults=false;recognition.continuous=false;recognition.onresult=event=>{$('input').value=event.results[0][0].transcript;invalidate();status('Voice captured. Click Translate.');};recognition.onerror=event=>status(`Microphone error: ${event.error}. You can still type your message.`,true);recognition.onend=()=>{recording=false;$('record').textContent='Start microphone';};}
$('record').onclick=()=>{if(!recognition){status('Speech recognition is unavailable. Try Chrome or Edge, or type your message.',true);return;}if(recording){recognition.stop();return;}recognition.lang=$('source').value;try{recognition.start();recording=true;$('record').textContent='Stop microphone';status('Listening… Speak one message.');}catch{status('Microphone could not start. Check browser permissions.',true);}};
$('input').addEventListener('keydown',event=>{if(event.ctrlKey&&event.key==='Enter')translate();});
async function init(){try{const response=await fetch('/api/languages');if(!response.ok)throw new Error();languages=await response.json();for(const id of ['source','target']){for(const [code,name]of Object.entries(languages))$(id).add(new Option(name,code));}$('source').value='en';$('target').value='fr';renderHistory();count();}catch{status('Cannot load languages. Keep the launcher terminal open and refresh.',true);$('translate').disabled=true;}}
init();
